print("/\\"*11)
print("\tProfile")
print("\\/"*11)
print("Name: ", end="\t")
input()
print("Age: " , end="\t")
input()
print("Hobby: ", end="\t")
input()
print("/\\"*11)
print ("\tProfile")
print("\\/"*11)
